---
title: "Cow/Sheep - DGE"
author: "Brandt Bessell"
date: "2023-03-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(DESeq2)
```

```{r}
# MODIFY THESE VARIABLES
setwd("C:/Users/bbessell/OneDrive - Michigan Medicine/Documents/Courses/BIOINF545/project/DGE")
rmdups <- F
hyper_geno <- "CN"
species <- "sheep"

# vector of srr codes
srr <- c("SRR1013842",
         "SRR1013845",
         "SRR1013850",
         "SRR1013855",
         "SRR1013857",
         "SRR1013871",
         "SRR1013874",
         "SRR1013877",
         "SRR1013879",
         "SRR1013888",
         "SRR1013898",
         "SRR1013904")

# genotypes, phenotypes, sample identifiers
geno <- c(rep("NN",3), rep("NC",3), rep("CN",3), rep("CC",3))
pheno <- c(rep("control", 3), rep("hyper", 3), rep("control",6))
samp_id <- c("NN_1",
             "NN_2",
             "NN_3",
             "NC_1",
             "NC_2",
             "NC_3",
             "CN_1",
             "CN_2",
             "CN_3",
             "CC_1",
             "CC_2",
             "CC_3")

# get all files, get subsets, ones with dupes removed, ones without
if (species=="cow"){
  all_files = list.files(path="./cow_counts", full.names=T)
} else {
  all_files = list.files(path="./sheep_counts", full.names=T)
}
cnt_files <- all_files[grep("^((?!_rmdup).)*$", all_files, perl=T)] # regex searches NOT contains '_rmdup'
cnt_files_rmdup <- all_files[grep("rmdup", all_files)] # vice versa

if (rmdups==T) {
  use_files <- cnt_files_rmdup
} else {
  use_files <- cnt_files # change this variable to change dupe use ^
}

# build count matrix
# could use the file reader for DESeq2, but Kate did that and I figured I'd do this way. 
# EdgeR might have a similar function as DESeq2 file reader
for (i in 1:length(srr)){
  for (j in 1:length(use_files)){
    if (grepl(srr[i], use_files[j])){
      if (i==1){
        cnt_df <- as.data.frame(read.table(use_files[j], header=F, sep="\t"))
        colnames(cnt_df)=c("gene", samp_id[i])
      } else{
        new_df <- as.data.frame(read.table(use_files[j],header=F, sep="\t"), col.names=c("gene",samp_id[i]))
        colnames(new_df)=c("gene", samp_id[i])
        cnt_df <- merge(cnt_df, new_df, by="gene", sort=F)
      }
    }
  }
}
cnt_df <- cnt_df[-grep("^_", cnt_df$gene),]  # drop qc rows
row.names(cnt_df) <- cnt_df$gene  # set rownames to genes
cnt_df[,"gene"] <- NULL  # remove gene column
count_matrix <- as.matrix(cnt_df)  # convert to matrix
```


```{r}
# make "dictionary" of sample info
# can set 'geno' to 'pheno' to compare against all non polar overdominant as one group
coldata <- data.frame(
  sample = samp_id,
  condition = geno, 
  row.names= "sample"
)
```

```{r}
# build DESeq2 object
dds <- DESeqDataSetFromMatrix(countData=count_matrix, colData=coldata, design = ~ condition)
dds <- dds[rowSums(counts(dds))>=6]  # 12 = dim 6? bc pairwise


# set hypertrophy gt as the first level, run deseq
# * note, CN vs NC is ambiguous
dds$condition <- relevel(dds$condition, ref=hyper_geno)  # hyper_geno
dds <- DESeq(dds, minReplicatesForReplace=Inf)
```

```{r}
# alpha = fdr cutoff
setwd("C:/Users/bbessell/OneDrive - Michigan Medicine/Documents/Courses/BIOINF545/project/DGE")
res <- results(dds, cooksCutoff=FALSE, independentFiltering=FALSE)
summary(results(dds, alpha=0.05))
write.csv(res, file=paste0("./results/DESeq2_Res_", hyper_geno, ".csv"))
```

```{r}
# pca, kate has better plotting stuff in her script
rld <- rlog(dds, blind=FALSE)
plotPCA(rld, intgroup=c("condition"))
```



```{r}
# try edgeR
library(limma)
library(edgeR)
library(ggplot2)
```
```{r}
which.maxn <- function(x,n=1){
  if (n==1)
    which.max(x)
  else
    {
      if (n>1){
        ii <- order(x,decreasing=TRUE)[1:min(n,length(x))]
        ii[!is.na(x[ii])]
      }
      else {
       stop("n must be >=1")
      }
    }
}
```


```{r}
library(tidyverse)
# filter count matrix to row counts >= number of dimensions
count_matrix <- count_matrix[rowSums(count_matrix)>=6,]
#count_matrix <- as.matrix(as.data.frame(count_matrix) %>% filter_all(all_vars(.>0)))
# remove outliers
count_matrix_filt <- count_matrix[-which.maxn(rowSums(count_matrix),n=2000),]
```

```{r}
mean_counts <- apply(count_matrix, 1, mean)        #The second argument '1' of 'apply' function indicates the function being applied to rows. Use '2' if applied to columns 
variance_counts <- apply(count_matrix, 1, var)
df <- data.frame(mean_counts, variance_counts)

ggplot2::ggplot(df, aes(x=mean_counts, y=variance_counts)) +
        geom_point(aes(x=mean_counts, y=variance_counts)) + 
        geom_smooth(method=lm, se=FALSE) +
        scale_y_log10(limits = c(1,1e9)) +
        scale_x_log10(limits = c(1,1e9)) +
        geom_abline(intercept = 0, slope = 1, color="red")
```

```{r}

for (i in 1:ncol(count_matrix_filt) ) {
  hist(count_matrix_filt[,i],
       main=paste0("Counts ", colnames(count_matrix_filt)[i]),
       breaks=50
  )
}
```

```{r}

# construct edgeR object, group/condition is genotype
dlist <- DGEList(counts=count_matrix, 
                 genes=row.names(count_matrix),
                 group=coldata$condition
                 )

dlist$samples$group <- relevel(dlist$samples$group, ref=hyper_geno)
dlist <- calcNormFactors(dlist, method="TMM")  # normalize
plotMDS(dlist)  # cluster
```


```{r}
# test groups against eachother
design_mat <- model.matrix(~0+group, data=dlist$samples)
print(design_mat)

# *** Don't really know what this does tbh
dlist <- estimateGLMCommonDisp(dlist, design=design_mat)
dlist <- estimateGLMTrendedDisp(dlist, design=design_mat)
dlist <- estimateGLMTagwiseDisp(dlist, design=design_mat)
```

```{r}

setwd("C:/Users/bbessell/OneDrive - Michigan Medicine/Documents/Courses/BIOINF545/project/DGE")
# fit that neg binom
fit <- glmQLFit(dlist, design_mat)

grp <- levels(dlist$samples$group)

print(grp)

# fix CN (or NC??) as control (even though it isnt the control)
for (i in 2:length(grp) ) {
  test <- grp[i]
  contrast <- rep(0, length(grp) )
  contrast[1] <- -1
  contrast[i] <- 1
  print(contrast)
  qlf <- glmQLFTest(fit, contrast=contrast)
  edgeR_result <- topTags(qlf, n=65000)
  deGenes <- decideTestsDGE(qlf, adjust.method="BH", p.value=0.05)
  deGenes <- rownames(qlf)[as.logical(deGenes)]
  expTab <- edgeR_result$table
  hist(expTab$PValue, main=paste0( hyper_geno, "vs", test))
  if (rmdups==T) {
    write.csv(expTab, file=paste0(
      "./results/rmdups_degenes_", species, "_", hyper_geno, "vs", test, ".csv"))
  } else {
    write.csv(expTab, file=paste0(
      "./results/degenes_", species, "_",  hyper_geno, "vs", test, ".csv"))
  }
}
```

```{r}
library(biomaRt)
```
```{r}
ensembl<-  useMart("ensembl", dataset="oaries_gene_ensembl")
gene_set <- c("LOC105606646", "DLK1", "RTL1")
conversion_table <- getBM(attributes=c("uniprot_gn_symbol", "ensembl_gene_id"), filters = "uniprot_gn_symbol", values = gene_set, mart= ensembl)

```


